"""Workday data-automation-id locators. Generated by ForgeDay."""

class Locators:
    """CSS selectors keyed off Workday data-automation-id values."""

    COOKIE_ACCEPT = "button[data-automation-id='legalNoticeAcceptButton']"
    COOKIE_ACCEPT_VARIANTS = ("#onetrust-accept-btn-handler", "button#onetrust-accept-btn-handler", "button[data-automation-id='wd-Accept']",)
    PROGRESS_BAR = "*[data-automation-id='progressBar']"
    PROGRESS_ACTIVE = "*[data-automation-id='progressBarActiveStep']"
    NEXT = "button[data-automation-id='bottom-navigation-next-button']"
    ERROR_BANNER = "*[data-automation-id='errorBanner']"
    ERROR_BANNER_VARIANTS = ("*[data-automation-id='errorMessage']",)
    ALREADY_APPLIED = "*[data-automation-id='alreadyApplied']"
    KEYWORD_SEARCH = "input[data-automation-id='keywordSearchInput']"
    KEYWORD_SEARCH_VARIANTS = ("input[data-automation-id='jobSearchInput']", "input[placeholder*='Search' i]",)
    SEARCH_BUTTON = "button[data-automation-id='keywordSearchButton']"
    SEARCH_BUTTON_VARIANTS = ("button[data-automation-id='searchButton']",)
    JOB_TITLE = "*[data-automation-id='jobTitle']"
    JOB_TITLE_VARIANTS = ("*[data-automation-id='promptOption']", "a[data-automation-id='jobTitle']",)
    JOB_LIST_ITEM = "*[data-automation-id='compositeContainer']"
    POSTING_TITLE = "*[data-automation-id='jobPostingHeader']"
    POSTING_TITLE_VARIANTS = ("*[data-automation-id='jobPostingTitle']",)
    APPLY = "*[data-automation-id='jobPostingApplyButton']"
    APPLY_VARIANTS = ("*[data-automation-id='adventureButton']", "a[data-automation-id='adventureButton']",)
    APPLY_MANUAL = "*[data-automation-id='applyManually']"
    CREATE_ACCOUNT = "*[data-automation-id='createAccountLink']"
    CREATE_ACCOUNT_VARIANTS = ("button[data-automation-id='createAccountLink']", "a[data-automation-id='createAccountLink']", "[aria-label='Create Account']",)
    SIGN_IN_WITH_EMAIL = "*[data-automation-id='signInWithEmail']"
    SIGN_IN_WITH_EMAIL_VARIANTS = ("button[data-automation-id='signInWithEmail']", "button[aria-label='Sign in with email']", "[role='button'][aria-label='Sign in with email']", "*[data-automation-id='emailSignInButton']",)
    EMAIL = "input[data-automation-id='email']"
    EMAIL_VARIANTS = ("input[type='email']", "input[name='email']", "input[autocomplete='username']", "input[autocomplete='email']",)
    PASSWORD = "input[data-automation-id='password']"
    PASSWORD_VARIANTS = ("input[type='password']", "input[name='password']", "input[autocomplete='current-password']",)
    VERIFY_PASSWORD = "input[data-automation-id='verifyPassword']"
    CREATE_ACCOUNT_CHECKBOX = "input[data-automation-id='createAccountCheckbox']"
    CREATE_ACCOUNT_CHECKBOX_VARIANTS = ("input[type='checkbox'][data-automation-id='createAccountCheckbox']", "input[data-automation-id='agreeToTermsCheckbox']", "[role='checkbox'][data-automation-id='createAccountCheckbox']",)
    SIGN_IN_SUBMIT = "button[data-automation-id='signInSubmitButton']"
    SIGN_IN_SUBMIT_VARIANTS = ("div[aria-label='Submit']", "div[role='button'][aria-label='Submit']", "[role='button'][aria-label='Submit']", "div[role='button'][data-automation-id='click_filter'][aria-label='Sign In']", "div[role='button'][aria-label='Sign In']", "button[type='submit'][data-automation-id='signInSubmitButton']",)
    CREATE_ACCOUNT_SUBMIT = "div[role='button'][data-automation-id='click_filter'][aria-label='Create Account']"
    INFO_PAGE = "*[data-automation-id='contactInformationPage']"
    PREVIOUS_WORKER = "*[data-automation-id='previousWorker']"
    COUNTRY = "button[data-automation-id='country']"
    FIRST_NAME = "input[data-automation-id='legalNameSection_firstName']"
    LAST_NAME = "input[data-automation-id='legalNameSection_lastName']"
    ADDRESS1 = "input[data-automation-id='addressSection_addressLine1']"
    CITY = "input[data-automation-id='addressSection_city']"
    REGION = "button[data-automation-id='addressSection_countryRegion']"
    POSTAL = "input[data-automation-id='addressSection_postalCode']"
    PHONE_TYPE = "button[data-automation-id='phone-device-type']"
    PHONE_TYPE_VARIANTS = ("button[data-automation-id='phoneType']",)
    PHONE = "input[data-automation-id='phone-number']"
    PHONE_VARIANTS = ("input[data-automation-id='phoneNumber']",)
    EXPERIENCE_PAGE = "*[data-automation-id='myExperiencePage']"
    WORK_SECTION = "*[data-automation-id='workExperienceSection']"
    WORK_ADD = "div[data-automation-id='workExperienceSection'] button[data-automation-id*='add' i]"
    WORK_PANEL_1 = "*[data-automation-id='workExperience-1']"
    WORK_JOB_TITLE = "input[data-automation-id='jobTitle']"
    WORK_COMPANY = "input[data-automation-id='company']"
    WORK_COMPANY_VARIANTS = ("input[data-automation-id='companyName']",)
    WORK_LOCATION = "input[data-automation-id='location']"
    CURRENTLY_HERE = "input[data-automation-id='currentlyWorkHere']"
    START_MONTH = "div[data-automation-id='formField-startDate'] input[data-automation-id='dateSectionMonth-input']"
    START_MONTH_VARIANTS = ("input[data-automation-id='startDate-dateSectionMonth']",)
    START_YEAR = "div[data-automation-id='formField-startDate'] input[data-automation-id='dateSectionYear-input']"
    ROLE_DESCRIPTION = "textarea[data-automation-id='description']"
    ROLE_DESCRIPTION_VARIANTS = ("textarea[data-automation-id='roleDescription']",)
    EDU_SECTION = "*[data-automation-id='educationSection']"
    SCHOOL = "div[data-automation-id='formField-schoolItem'] input"
    SCHOOL_VARIANTS = ("div[data-automation-id='formField-schoolName'] input",)
    DEGREE = "div[data-automation-id='formField-degree'] button"
    SKILLS = "*[data-automation-id='formField-skills']"
    SKILLS_VARIANTS = ("*[data-automation-id='formField-skillsPrompt']",)
    MULTISELECT = "*[data-automation-id='multiselectInputContainer']"
    MONIKER_SEARCH = "input[data-automation-id='monikerSearchBox']"
    RESUME_INPUT = "input[data-automation-id='file-upload-input-ref']"
    RESUME_INPUT_VARIANTS = ("div[data-automation-id='resumeSection'] input[type='file']",)
    LINKEDIN = "input[data-automation-id='linkedinQuestion']"
    QUESTIONS_PAGE = "*[data-automation-id='applyFlowPrimaryQuestionsPage']"
    QUESTIONS_PAGE_2 = "*[data-automation-id='applyFlowSecondaryQuestionsPage']"
    DISCLOSURES_PAGE = "*[data-automation-id='voluntaryDisclosuresPage']"
    GENDER = "button[data-automation-id='gender']"
    ETHNICITY = "button[data-automation-id='ethnicityDropdown']"
    VETERAN = "button[data-automation-id='veteranStatus']"
    AGREEMENT = "input[data-automation-id='agreementCheckbox']"
    SELF_ID_PAGE = "*[data-automation-id='selfIdentificationPage']"
    SELF_ID_NAME = "div[data-automation-id='selfIdentificationPage'] input[data-automation-id='name']"
    SUBMIT = "button[data-automation-id='bottom-navigation-save-and-submit-button']"
    SUBMIT_VARIANTS = ("button[aria-label='Submit']", "button[aria-label='Save and Submit']", "button[data-automation-id='submitButton']",)
    PROMPT_OPTION = "*[data-automation-id='promptOption']"
